export const POST_COMPANY_DATA_REQUEST = "POST_COMPANY_DATA_REQUEST";
export const POST_COMPANY_DATA_SUCCESS = "POST_COMPANY_DATA_SUCCESS";
export const POST_COMPANY_DATA_FAIL = "POST_COMPANY_DATA_FAIL";
export const POST_COMPANY_DATA_RESET = "POST_COMPANY_DATA_RESET";

export const PUT_COMPANY_DATA_REQUEST = "PUT_COMPANY_DATA_REQUEST";
export const PUT_COMPANY_DATA_SUCCESS = "PUT_COMPANY_DATA_SUCCESS";
export const PUT_COMPANY_DATA_FAIL = "PUT_COMPANY_DATA_FAIL";
export const PUT_COMPANY_DATA_RESET = "PUT_COMPANY_DATA_RESET";
