export const POST_COMPANY_DATA_REQUEST = "POST_COMPANY_DATA_REQUEST";
export const POST_COMPANY_DATA_SUCCESS = "POST_COMPANY_DATA_SUCCESS";
export const POST_COMPANY_DATA_FAIL = "POST_COMPANY_DATA_FAIL";
